# Generated by Django 3.2.5 on 2022-07-22 10:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbListings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('listing_url', models.CharField(max_length=1000)),
                ('last_scraped', models.DateField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('host_id', models.IntegerField()),
                ('host_name', models.CharField(max_length=1000)),
                ('host_since', models.CharField(max_length=1000)),
                ('host_location', models.CharField(max_length=1000)),
                ('host_total_listings_count', models.IntegerField()),
                ('neighbourhood_cleansed', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.CharField(max_length=1000)),
                ('accommodates', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('price', models.FloatField()),
                ('minimum_nights_avg_ntm', models.FloatField()),
                ('availability_30', models.IntegerField()),
                ('availability_60', models.IntegerField()),
                ('availability_90', models.IntegerField()),
                ('availability_365', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('number_of_reviews_ltm', models.IntegerField()),
                ('number_of_reviews_l30d', models.IntegerField()),
                ('license', models.CharField(max_length=1000)),
                ('instant_bookable', models.CharField(max_length=1000)),
                ('calculated_host_listings_count', models.IntegerField()),
                ('reviews_per_month', models.FloatField()),
                ('days_rented_ltm', models.FloatField()),
                ('rounded_revenue_ltm', models.FloatField()),
                ('occupancy_rate_approx', models.FloatField()),
                ('is_hotel', models.IntegerField()),
                ('is_entire', models.IntegerField()),
                ('many_listings', models.IntegerField()),
                ('only_1_listing', models.IntegerField()),
                ('only_2_listings', models.IntegerField()),
                ('host_florence', models.IntegerField()),
                ('has_liscense', models.IntegerField()),
                ('is_instant_bookable', models.IntegerField()),
                ('dist_duomo', models.FloatField()),
                ('is_centro', models.IntegerField()),
                ('is_gavinana', models.IntegerField()),
                ('is_isolotto', models.IntegerField()),
                ('is_rifredi', models.IntegerField()),
                ('is_campo', models.IntegerField()),
                ('listing_revenue_exceed_LTR', models.IntegerField()),
                ('effected_by_policy_1', models.IntegerField()),
                ('effected_by_policy_2', models.IntegerField()),
                ('effected_by_policy_3', models.IntegerField()),
                ('commercial', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geo')),
            ],
        ),
    ]
