# Generated by Django 3.2.5 on 2022-07-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnblistings',
            name='geom',
        ),
    ]
