# Generated by Django 3.2.5 on 2022-07-26 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_remove_airbnblistings_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnblistings',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='0101000000000000000000F03F000000000000F03F', srid=4326, verbose_name='geo'),
            preserve_default=False,
        ),
    ]
